name: Hux
version: 1.2 # 수정 가능
main: kr.vanilage.main.Main
api-version: '1.20' # 수정 가능

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.10 # Kotlin 버전을 수정하세요.
  - io.github.monun:kommand-core:3.1.7
  - io.github.monun:invfx-core:3.3.2